-- Generated from theme/palette.ts by theme/build.ts. Do not edit.
vim.g.colors_name = 'gg-light'
vim.o.background = 'light'

local hi = function(name, val) vim.api.nvim_set_hl(0, name, val) end
local link = function(from, to) vim.api.nvim_set_hl(0, from, { link = to }) end

-- Editor UI
hi('Normal',         { fg = '#0f130e', bg = '#e0e2df' })
hi('NormalFloat',    { fg = '#0f130e', bg = '#d1d6cf', blend = 10 })
hi('NormalNC',       { fg = '#0f130e', bg = '#e0e2df' })
hi('FloatBorder',    { fg = '#6b7268', bg = '#d1d6cf', blend = 10 })
hi('FloatTitle',     { fg = '#0f130e', bg = '#d1d6cf', bold = true, blend = 10 })
hi('ColorColumn',    { bg = '#d1d6cf' })
hi('Conceal',        { fg = '#6b7268' })
hi('Cursor',         { fg = '#e0e2df', bg = '#0f130e' })
hi('lCursor',        { fg = '#e0e2df', bg = '#0f130e' })
hi('CursorIM',       { fg = '#e0e2df', bg = '#0f130e' })
hi('CursorColumn',   { bg = '#d1d6cf' })
hi('CursorLine',     { bg = '#d1d6cf' })
hi('CursorLineFold', { bg = '#d1d6cf' })
hi('CursorLineNr',   { fg = '#0f130e', bg = '#d1d6cf', bold = true })
hi('CursorLineSign', { bg = '#d1d6cf' })
hi('Directory',      { fg = '#006168' })
hi('EndOfBuffer',    { fg = '#e0e2df' })
hi('ErrorMsg',       { fg = '#940033' })
hi('WinSeparator',   { fg = '#6b7268' })
hi('Folded',         { fg = '#3f443c', bg = '#d1d6cf' })
hi('FoldColumn',     { fg = '#6b7268', bg = '#e0e2df' })
hi('SignColumn',     { fg = '#6b7268', bg = '#e0e2df' })
hi('IncSearch',      { fg = '#e0e2df', bg = '#9b1a00' })
hi('Substitute',     { fg = '#e0e2df', bg = '#9b1a00' })
hi('LineNr',         { fg = '#6b7268' })
hi('LineNrAbove',    { fg = '#6b7268' })
hi('LineNrBelow',    { fg = '#6b7268' })
hi('MatchParen',     { fg = '#0f130e', bg = '#6b7268', bold = true })
hi('ModeMsg',        { fg = '#0f130e', bold = true })
hi('MsgArea',        { fg = '#0f130e' })
hi('MsgSeparator',   { fg = '#6b7268' })
hi('MoreMsg',        { fg = '#006168' })
hi('NonText',        { fg = '#6b7268' })
hi('Pmenu',          { fg = '#0f130e', bg = '#d1d6cf', blend = 8 })
hi('PmenuSel',       { fg = '#0f130e', bg = '#d8a8b9' })
hi('PmenuKind',      { fg = '#006168', bg = '#d1d6cf', blend = 8 })
hi('PmenuKindSel',   { fg = '#006168', bg = '#d8a8b9' })
hi('PmenuExtra',     { fg = '#3f443c', bg = '#d1d6cf', blend = 8 })
hi('PmenuExtraSel',  { fg = '#3f443c', bg = '#d8a8b9' })
hi('PmenuSbar',      { bg = '#d1d6cf', blend = 8 })
hi('PmenuThumb',     { bg = '#6b7268' })
hi('Question',       { fg = '#006168' })
hi('QuickFixLine',   { bg = '#d1d6cf', bold = true })
hi('Search',         { fg = '#0f130e', bg = '#ded1a9' })
hi('CurSearch',      { fg = '#e0e2df', bg = '#9b1a00' })
hi('SpecialKey',     { fg = '#6b7268' })
hi('SpellBad',       { undercurl = true, sp = '#940033' })
hi('SpellCap',       { undercurl = true, sp = '#9b1a00' })
hi('SpellLocal',     { undercurl = true, sp = '#006168' })
hi('SpellRare',      { undercurl = true, sp = '#0052c8' })
hi('StatusLine',     { fg = '#0f130e', bg = '#d1d6cf' })
hi('StatusLineNC',   { fg = '#3f443c', bg = '#d1d6cf' })
hi('TabLine',        { fg = '#3f443c', bg = '#d1d6cf' })
hi('TabLineFill',    { bg = '#d1d6cf' })
hi('TabLineSel',     { fg = '#0f130e', bg = '#e0e2df', bold = true })
hi('Title',          { fg = '#0052c8', bold = true })
hi('Visual',         { bg = '#a9c09d' })
hi('VisualNOS',      { bg = '#a9c09d' })
hi('WarningMsg',     { fg = '#9b1a00' })
hi('Whitespace',     { fg = '#6b7268' })
hi('WildMenu',       { fg = '#0f130e', bg = '#d8a8b9' })
hi('WinBar',         { fg = '#0f130e', bg = '#e0e2df', bold = true })
hi('WinBarNC',       { fg = '#3f443c', bg = '#e0e2df' })

-- Diff
hi('DiffAdd',    { bg = '#c8dfc8' })
hi('DiffChange', { bg = '#c4daf2' })
hi('DiffDelete', { bg = '#f1cdd0' })
hi('DiffText',   { bg = '#c4daf2', underline = true })
hi('Added',      { fg = '#006400' })
hi('Changed',    { fg = '#9b1a00' })
hi('Removed',    { fg = '#940033' })

-- Syntax
hi('Comment',        { fg = '#3f443c', italic = true })
hi('Constant',       { fg = '#0052c8' })
hi('String',         { fg = '#633800' })
hi('Character',      { fg = '#633800' })
hi('Number',         { fg = '#0052c8' })
hi('Boolean',        { fg = '#0052c8' })
hi('Float',          { fg = '#0052c8' })
hi('Identifier',     { fg = '#0f130e' })
hi('Function',       { fg = '#006400' })
hi('Statement',      { fg = '#7f1087' })
hi('Conditional',    { fg = '#7f1087' })
hi('Repeat',         { fg = '#7f1087' })
hi('Label',          { fg = '#7f1087' })
hi('Operator',       { fg = '#7f1087' })
hi('Keyword',        { fg = '#7f1087' })
hi('Exception',      { fg = '#7f1087' })
hi('PreProc',        { fg = '#7f1087' })
hi('Include',        { fg = '#7f1087' })
hi('Define',         { fg = '#7f1087' })
hi('Macro',          { fg = '#7f1087' })
hi('PreCondit',      { fg = '#7f1087' })
hi('Type',           { fg = '#006168', italic = true })
hi('StorageClass',   { fg = '#7f1087' })
hi('Structure',      { fg = '#006168' })
hi('Typedef',        { fg = '#006168' })
hi('Special',        { fg = '#7f1087' })
hi('SpecialChar',    { fg = '#7f1087' })
hi('Tag',            { fg = '#7f1087' })
hi('Delimiter',      { fg = '#0f130e' })
hi('SpecialComment', { fg = '#3f443c', bold = true })
hi('Debug',          { fg = '#940033' })
hi('Underlined',     { fg = '#006168', underline = true })
hi('Ignore',         {})
hi('Error',          { fg = '#940033' })
hi('Todo',           { fg = '#006168', bold = true })

-- Diagnostics
hi('DiagnosticError',            { fg = '#940033' })
hi('DiagnosticWarn',             { fg = '#9b1a00' })
hi('DiagnosticInfo',             { fg = '#006168' })
hi('DiagnosticHint',             { fg = '#006400' })
hi('DiagnosticOk',               { fg = '#006400' })
hi('DiagnosticUnderlineError',   { undercurl = true, sp = '#940033' })
hi('DiagnosticUnderlineWarn',    { undercurl = true, sp = '#9b1a00' })
hi('DiagnosticUnderlineInfo',    { undercurl = true, sp = '#006168' })
hi('DiagnosticUnderlineHint',    { undercurl = true, sp = '#006400' })
hi('DiagnosticUnderlineOk',      { undercurl = true, sp = '#006400' })
hi('DiagnosticVirtualTextError', { fg = '#940033' })
hi('DiagnosticVirtualTextWarn',  { fg = '#9b1a00' })
hi('DiagnosticVirtualTextInfo',  { fg = '#006168' })
hi('DiagnosticVirtualTextHint',  { fg = '#006400' })
hi('DiagnosticSignError',        { fg = '#940033' })
hi('DiagnosticSignWarn',         { fg = '#9b1a00' })
hi('DiagnosticSignInfo',         { fg = '#006168' })
hi('DiagnosticSignHint',         { fg = '#006400' })

-- LSP
hi('LspReferenceText',            { bg = '#d1d6cf' })
hi('LspReferenceRead',            { bg = '#d1d6cf' })
hi('LspReferenceWrite',           { bg = '#d1d6cf', underline = true })
hi('LspSignatureActiveParameter', { fg = '#9b1a00', bold = true })
hi('LspInlayHint',                { fg = '#3f443c', bg = '#d1d6cf' })
hi('LspCodeLens',                 { fg = '#6b7268' })
hi('LspCodeLensSeparator',        { fg = '#6b7268' })

-- Treesitter
link('@variable',              'Identifier')
link('@variable.builtin',      'Keyword')
hi('@variable.parameter',      { fg = '#9b1a00', italic = true })
link('@variable.member',       'Identifier')
link('@constant',              'Constant')
link('@constant.builtin',      'Constant')
link('@constant.macro',        'Macro')
link('@module',                'Structure')
link('@label',                 'Label')
link('@string',                'String')
hi('@string.regexp',           { fg = '#940033' })
link('@string.escape',         'SpecialChar')
link('@string.special',        'Special')
link('@character',             'Character')
link('@character.special',     'SpecialChar')
link('@boolean',               'Boolean')
link('@number',                'Number')
link('@number.float',          'Float')
link('@type',                  'Type')
link('@type.builtin',          'Type')
link('@type.definition',       'Type')
link('@attribute',             'PreProc')
link('@property',              'Identifier')
link('@function',              'Function')
hi('@function.builtin',        { fg = '#006168' })
link('@function.call',         'Function')
link('@function.macro',        'Macro')
link('@function.method',       'Function')
link('@function.method.call',  'Function')
hi('@constructor',             { fg = '#006168' })
link('@operator',              'Operator')
link('@keyword',               'Keyword')
link('@keyword.conditional',   'Conditional')
link('@keyword.repeat',        'Repeat')
link('@keyword.return',        'Keyword')
link('@keyword.function',      'Keyword')
link('@keyword.operator',      'Operator')
link('@keyword.import',        'Include')
link('@keyword.exception',     'Exception')
link('@punctuation.bracket',   'Delimiter')
link('@punctuation.delimiter', 'Delimiter')
link('@punctuation.special',   'Special')
link('@comment',               'Comment')
link('@comment.documentation', 'Comment')
link('@tag',                   'Tag')
hi('@tag.attribute',           { fg = '#006400', italic = true })
link('@tag.delimiter',         'Delimiter')
link('@markup.heading',        'Title')
hi('@markup.italic',           { italic = true })
hi('@markup.strong',           { bold = true })
link('@markup.underline',      'Underlined')
hi('@markup.strikethrough',    { strikethrough = true })
link('@markup.link',           'Underlined')
hi('@markup.link.url',         { fg = '#006168', underline = true })
hi('@markup.raw',              { fg = '#006400' })
hi('@markup.list',             { fg = '#7f1087' })
